# Numpy Library operations

In [4]:
import numpy as np

## Creating a one dimension array

In [88]:
arr = np.array([1,2,3,4,5,7,6,6])
print(arr)

[1 2 3 4 5 7 6 6]


## Creating a 2D array

In [18]:
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


## Creating 3D array

In [22]:
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,9]]])
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 9]]])

## Finding Shape of array

In [96]:
print(arr2d.shape)

(2, 3)


## Finding the dimension of array

In [98]:
print(arr2d.ndim)

2


## Len of array

In [100]:
print(len(arr2d))

2


## Size of array

In [38]:
arr.size

5

In [40]:
arr2d.size

6

In [42]:
arr3d.size


8

## Finding the type of element in array

In [106]:
print(arr2d.dtype)

int32


## Creating Specials array

### Array of Zeros

In [66]:
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


### Arrays of Ones

In [72]:
one = np.ones((2,4,8))
print(one)

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


### Identity matrix

In [76]:
iden = np.eye(4)
print(iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Creating Array with Random Numbers

In [84]:
random_array = np.random.rand(2,3)
print(random_array)

[[0.85238427 0.91984499 0.42165763]
 [0.08668586 0.20301418 0.52885703]]


### Exercises

In [131]:
import numpy as np

# Create a 2D array with numbers from 10 to 49 (40 elements to fit into 4x5)
array = np.arange(10, 30).reshape(4, 5)

print("2D NumPy array filled with numbers from 10 to 49:")
print(array)


2D NumPy array filled with numbers from 10 to 49:
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [5]:
import numpy as np

# Generate an array of 20 equally spaced numbers between 5 and 15
array = np.linspace(5,15,20)

print(" Array of 20 equally spaced numbers between 5 and 15: ")
print(array)

 Array of 20 equally spaced numbers between 5 and 15 
[ 5.          5.52631579  6.05263158  6.57894737  7.10526316  7.63157895
  8.15789474  8.68421053  9.21052632  9.73684211 10.26315789 10.78947368
 11.31578947 11.84210526 12.36842105 12.89473684 13.42105263 13.94736842
 14.47368421 15.        ]


In [13]:
import numpy as np \

#  Generate an Array of random number between 1 and 101 0f size 3 x 3 
array = np.random.randint(1,101, size = (3,3))

print("Array of random number between 1 and 101 0f size 3 x 3 ")
print(array)

Array of random number between 1 and 101 0f size 3 x 3 
[[14 15 98]
 [80 89 35]
 [80 62 86]]


In [21]:
## Conveting datatype of element in an array

import numpy as np 

# Creating array
arr = np.array([1,2,3,4,5])

print("Orginal array: ", arr)
print("Orginal array datatypes: ", arr.dtype)

if arr.dtype != np.float64:
    arr = arr.astype(np.float64)

print("\nModified array: ", arr)
print("Modified array datatypes: ", arr.dtype)

Orginal array:  [1 2 3 4 5]
Orginal array datatypes:  int32

Modified array:  [1. 2. 3. 4. 5.]
Modified array datatypes:  float64


In [35]:
import numpy as np

# Creating two arrya with int and float datatype

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1.1,2.2, 3.3, 4.4, 5.5])

def process_array(arr):
    if np.issubdtype(arr.dtype , np.integer):
        print("Array contains only integers. Processing...")
        arr = arr.astype(np.float64) + 0.5 
    else:
        print("Array does not contain only integers. No changes made.")
    return arr

# Test the function on the arrays
process_array1 = process_array(arr1)
process_array2 = process_array(arr2)

print("Orginal array 1: ", arr1)
print("P[rocess array 1: ", process_array1)
print("Orginal array 2: ", arr2)
print("Process array 2: ", process_array2)

Array contains only integers. Processing...
Array does not contain only integers. No changes made.
Orginal array 1:  [1 2 3 4 5]
P[rocess array 1:  [1.5 2.5 3.5 4.5 5.5]
Orginal array 2:  [1.1 2.2 3.3 4.4 5.5]
Process array 2:  [1.1 2.2 3.3 4.4 5.5]


In [41]:
import numpy as np 

zero = np.zeros((4,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [43]:
import numpy as np 

one = np.ones((3,5))
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [45]:
import numpy as np

iden = np.eye(5)
print(iden)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [49]:
import numpy as np 

random_array = np.random.random((3,4))

rounded_array = np.round(random_array , 2)

print("Orignal array with random numbers.")
print(random_array)

print("Array with rounded number ti 2 decimal placve")
print(rounded_array)

Orignal array with random numbers.
[[0.79885241 0.69655116 0.47574623 0.31589414]
 [0.48155971 0.17621526 0.50542082 0.44475409]
 [0.09716199 0.45250377 0.08871718 0.13147399]]
Array with rounded number ti 2 decimal placve
[[0.8  0.7  0.48 0.32]
 [0.48 0.18 0.51 0.44]
 [0.1  0.45 0.09 0.13]]


## Mathematical Operation using Numpy

In [6]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,2,3,1])

add = arr1 + arr2
sub = arr2-arr1
product = arr1*arr2
div = arr2/arr1

print("Addition: ",add)
print("Subtraction: ",sub)
print("Multiplication: ", product)
print("Division: ",div)

Addition:  [6 6 5 7 6]
Subtraction:  [ 4  2 -1 -1 -4]
Multiplication:  [ 5  8  6 12  5]
Division:  [5.         2.         0.66666667 0.75       0.2       ]


## Aggregation with numpy

In [14]:
data = [1,23,45,67,89,3,2,14,56]

Sum = np.sum(data)
Mean = np.mean(data)
Std = np.std(data)
Median = np.median(data)

print(f"Sum of all the data is: {Sum}")
print(f"Mean of the data is: {Mean}")
print(f"Standard Deviation of data is: {Std}")
print(f"Median of the data is: {Median}")

Sum of all the data is: 300
Mean of the data is: 33.333333333333336
Standard Deviation of data is: 30.38640046687553
Median of the data is: 23.0


In [16]:
## Reshaping and resizing array and matrix

In [20]:
## reshaping an array

array = np.arange(12)

reshape_3x4 = array.reshape(3,4)
reshape_2x6 = array.reshape(2,6)

print("3x4 Matrix:\n", reshape_3x4)
print("2x6 Matrix:\n", reshape_2x6)

3x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2x6 Matrix:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [30]:
## Resizing matrix to array
matrix = np.array([[1,2,3],[4,5,6],[6,9,8]])
flattened = matrix.flatten()

print(f"Flattened Array: {flattened}")

Flattened Array: [1 2 3 4 5 6 6 9 8]


In [34]:
arr = np.array([[1,2,3],[4,5,6],[6,9,8]])

#finding any spedific element like 5 in this case
element = arr[1,1]
print(element)

#printing any specific row
row_3 = arr[2,:]
print(row_3)

middle_col = arr[:,1]
print(middle_col)

5
[6 9 8]
[2 5 9]


In [44]:
## Slicing 

arr = np.arange(12)
first_5 = arr[:5]
last_5 =  arr[7:]
every_2nd = arr[::2]

print(f"First 5 element of array: {first_5}")
print(f"Last 5 element of array: {last_5}")
print(f"Every element of array: {every_2nd}")

First 5 element of array: [0 1 2 3 4]
Last 5 element of array: [ 7  8  9 10 11]
Every element of array: [ 0  2  4  6  8 10]


In [50]:
# Generate a 5x5 matrix where each element is the square of its row index
rows = np.arange(5).reshape(-1,1)
matrix = rows**2
print(matrix)

[[ 0]
 [ 1]
 [ 4]
 [ 9]
 [16]]


In [60]:
# Replace values greater than 50 with 0
random_array = np.random.randint(1,50,10)
random_array[random_array >30] = 0
print(random_array)

[23  0  0  0  7  0  0  0  0  0]


In [62]:
# Create a diagonal matrix
diag_matrix = np.diag([10, 20, 30, 40])
print("Diagonal Matrix:\n", diag_matrix)

# Function to generate n x n random matrix
def random_matrix(n):
    return np.random.randint(1, 100, (n, n))

print("\n5x5 Random Matrix:\n", random_matrix(5))

# Create a 3D array and extract a sub-array
array_3d = np.random.randint(1, 100, (2, 3, 4))  # Shape (2, 3, 4)
sub_array = array_3d[0, :, :]  # Extract the first "layer"
print("\nOriginal 3D Array:\n", array_3d)
print("\n2x4 Sub-array:\n", sub_array[:, :2])  # Extract a 2x4 sub-array


Diagonal Matrix:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]

5x5 Random Matrix:
 [[65  1 46 43 12]
 [56 63  3 31 56]
 [52 82 61 35 57]
 [63 71 71 95 96]
 [43 13 29 11 16]]

Original 3D Array:
 [[[90 49  5  5]
  [54 58 45 81]
  [29 75 20 97]]

 [[40 86 61 80]
  [94 63 28 50]
  [81 51 49 19]]]

2x4 Sub-array:
 [[90 49]
 [54 58]
 [29 75]]


In [10]:
x = np.random.normal(size=50)
x

array([ 1.98931181e-01, -1.69679397e+00,  7.88245388e-01, -2.00992879e-03,
        4.37156929e-01,  1.84437488e+00,  6.89268923e-01, -3.18115881e-01,
        3.76754425e-01, -9.87486410e-01, -1.39025914e+00, -7.12186787e-01,
        1.03723614e+00, -9.59622266e-01, -1.71880737e+00, -5.23264424e-01,
       -4.32673921e-01,  2.00005057e+00,  5.95227943e-01, -2.72902229e+00,
        3.20376378e-01, -3.81532664e-01,  7.27434226e-01,  1.52768004e+00,
       -9.08873733e-01, -1.53661236e+00, -7.50569318e-02,  2.02420240e-01,
       -1.92792874e+00, -1.96340825e+00, -4.98705525e-01,  4.58616335e-02,
        3.59551243e-01, -2.31919307e-01,  2.05949425e-01,  1.09921088e+00,
       -3.64130111e-01, -1.12163453e+00, -3.93999346e-01, -5.51985203e-01,
        1.83775655e-01,  7.14131281e-02,  2.65411206e-01,  2.13212098e+00,
       -1.26130347e+00, -4.04086687e-01,  7.78393192e-01, -5.04081490e-01,
        4.87124559e-01,  1.81502982e+00])

In [12]:
y = x + np.random.normal(loc=50, scale=1, size=50)
y

array([49.96837954, 49.92955794, 52.0793415 , 50.28256343, 48.7761297 ,
       52.0246958 , 50.30224344, 49.95178287, 49.63303659, 49.1061186 ,
       48.9425921 , 48.88988634, 51.30175124, 49.42733794, 47.72945355,
       49.74605148, 49.38082901, 52.9896538 , 49.61228901, 45.14198819,
       49.21281613, 50.19305093, 49.46359203, 51.65921098, 48.47624891,
       49.68487373, 50.62402394, 49.67841839, 47.79603838, 48.50638418,
       50.43200448, 49.32317253, 50.6774542 , 50.27737999, 50.61870956,
       49.12800984, 49.3313797 , 49.32914072, 50.06637094, 49.92739921,
       51.00978489, 51.09048537, 48.85885279, 52.06250901, 50.18707816,
       49.02554711, 50.62850229, 50.19578088, 52.1822941 , 49.74894658])

In [14]:
np.corrcoef(x,y)

array([[1.        , 0.71600291],
       [0.71600291, 1.        ]])

### Using `np.where()` for Conditional Selection

In [ ]:
arr = np.array([10, 15, 20, 25, 30])
result = np.where(arr > 20)
print("Indices where arr > 20:", result)

### Logical Checks with np.any() and np.all()

In [ ]:
arr = np.array([True, False, True])
print("Any True:", np.any(arr))
print("All True:", np.all(arr))

### Set Operations

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
print("Union:", np.union1d(a, b))
print("Intersection:", np.intersect1d(a, b))
print("Set Difference (a - b):", np.setdiff1d(a, b))

### Broadcasting Example

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
broadcasted = arr + 10
print(broadcasted)

### Boolean Indexing

In [ ]:
arr = np.array([5, 10, 15, 20, 25])
print("Elements greater than 15:", arr[arr > 15])

### Using np.clip() to Limit Values

In [ ]:
arr = np.array([10, 50, 100, 150])
clipped = np.clip(arr, 30, 120)
print("Clipped Array:", clipped)

### Understanding Copy vs View in NumPy

In [ ]:
arr = np.array([1, 2, 3, 4])
view_arr = arr.view()
copy_arr = arr.copy()

arr[0] = 99
print("Original:", arr)
print("View:", view_arr)
print("Copy:", copy_arr)

### Random Sampling using np.random

In [ ]:
rand_arr = np.random.randint(1, 100, size=(3, 3))
print("Random Integer Array:\n", rand_arr)

### Linear Algebra Operations

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Dot product:\n", np.dot(a, b))
print("Matrix inverse:\n", np.linalg.inv(np.array([[1, 2], [3, 4]])))

### Saving and Loading NumPy Arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
np.save('my_array.npy', arr)
loaded = np.load('my_array.npy')
print("Loaded Array:", loaded)

## Summary

In this notebook, I covered key NumPy operations including array creation, reshaping, mathematical operations, conditional selections, broadcasting, and more. This provides a solid foundation for data analysis and scientific computing with Python.